name: RunUnitTests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: InstallPython3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: RunTests
        run: |
          chmod 755 runAllTests.sh
          ./runAllTests.sh
